"""
Django settings for djangoref project.

Generated by 'django-admin startproject' using Django 1.11.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os
from django.utils.translation import gettext_lazy as _

import django
from django.utils.translation import gettext
django.utils.translation.ugettext = gettext


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

LANGUAGES = (
    ('ca', _('Catalan')),
    ('en', _('English')),
)

LOCALE_PATHS = (
   os.path.join(BASE_DIR, 'locale'),
)

# create language
# django-admin.py makemessages -l en
# django-admin.py makemessages -d djangojs -l en
# django-admin.py makemessages -l ca
# django-admin.py makemessages -d djangojs -l ca
# compile languages
# django-admin.py compilemessages

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# OVERRIDEN IN SETTINGS_LOCAL
SECRET_KEY = 'gx%(-$i!e@y9o-xa^=962t*f-ngn-!u+zf)m-$icedw8pzb@&s'

# SECURITY WARNING: don't run with debug turned on in production!
# OVERRIDEN IN SETTINGS_LOCAL
DEBUG = os.environ.get("DEBUG", False)

# OVERRIDEN IN SETTINGS_LOCAL
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    #'material',
    #'material.admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'bootstrap3',
    'georef',
    'georef_addenda',
    'djangobower',
    'ajaxuploader',
    "bootstrap_datepicker_plus",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'georef.middleware.ForceDefaultLanguageMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangoref.urls'

# Fix for bootstrap_datepicker_plus. Using local files; but bug should be fixed on next official release
# Current version gives
# Deprecate Mutation Events (Deprecated) on current browsers
DOMAIN = 'localhost'
BOOTSTRAP_DATEPICKER_PLUS = {    
    "app_static_url": f"http{'s' if not DEBUG else ''}://{DOMAIN}{':8000' if DEBUG else ''}/static/georef/javascript/bootstrap_datepicker_plus/",
}

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'georef.context_processors.revision_number_processor',
                'georef.context_processors.version_number_processor',
                'georef.context_processors.custom_util_links_processor',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangoref.wsgi.application'


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'ca'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

DATABASES = {
    'default': {
        'ENGINE': os.environ.get("SQL_ENGINE", 'django.contrib.gis.db.backends.postgis'),
        'NAME': os.environ.get("SQL_DATABASE", os.path.join(BASE_DIR, "postgres")),
        'USER': os.environ.get("SQL_USER", "postgres"),
        'PASSWORD': os.environ.get("SQL_PASSWORD", ""),
        'HOST': os.environ.get("SQL_HOST", "db"),
        'PORT': os.environ.get("SQL_PORT", "5432")
    }
}


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

# OVERRIDEN IN SETTINGS_LOCAL
STATIC_ROOT = '/home/webuser/dev/django/djangoref/static/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

LOGIN_URL = '/login'

LOCAL_DATAFILE_ROOT_DIRECTORY = 'helpfile_uploads'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'djangobower.finders.BowerFinder',
]

# ./manage.py bower install
# BOWER_INSTALLED_APPS = (
#     'jquery',
#     'jquery-ui',
#     'datatables.net',
#     'datatables.net-dt',
#     'popper.js',
#     'bootstrap',
#     'toastr',
#     'jstree',
#     'jquery-tagit',
# )
BOWER_INSTALLED_APPS = (
	'bootstrap#3.3.7',
 	'datatables.net#1.10.16',
 	'datatables.net-dt#3.2.2',
 	'jquery#3.3.1',
 	'jquery-tagit#6ccd2de95e7cf7e254ad1a82e946450c21e40421',
 	'jquery-ui#1.12.1',
 	'jstree#3.3.5',
 	'popper.js#1.14.1',
 	'toastr#2.1.3'
)

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25
}

MEDIA_URL = '/media/'
# Media root
UPLOAD_DIR = BASE_DIR + "/uploads"
LOCAL_DATAFILE_ROOT_DIRECTORY = 'helpfile_uploads'
MEDIA_ROOT = UPLOAD_DIR
STATIC_ROOT = '/public_html/djangoref/static/'

#GEOSERVER STUFF
#DO NOT CHANGE THIS VALUE!
GEOSERVER_WORKSPACE = 'mzoologia'
GEOSERVER_USER = os.environ.get("GEOSERVER_ADMIN_USER", 'admin')
GEOSERVER_PASSWORD = os.environ.get("GEOSERVER_ADMIN_PASSWORD", 'geoserver')
GEOSERVER_EXTERNAL_URL = 'http://127.0.0.1:8080/'
GEOSERVER_BASE_URL = 'http://geoserver:8080/'
GEOSERVER_WMS_URL_CLEAN = GEOSERVER_BASE_URL + 'geoserver/wms/'
GEOSERVER_WMS_URL_CLEAN_EXTERNAL = GEOSERVER_EXTERNAL_URL + 'geoserver/wms/'
GEOSERVER_REST_URL = GEOSERVER_BASE_URL + 'geoserver/rest/'
GEOSERVER_WMS_URL = GEOSERVER_EXTERNAL_URL + 'geoserver/' + GEOSERVER_WORKSPACE + "/wms/?"

BING_MAPS_API_KEY = os.environ.get("BING_MAPS_API_KEY", "")

CSRF_TRUSTED_ORIGINS = ['http://127.0.0.1:1337']

try:
    from djangoref.settings_local import *
except ModuleNotFoundError:
    pass

#5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760

JAVASCRIPT_VERSION = 112

#Semver versioning - https://semver.org/
MAJOR="1"
MINOR="1"
PATCH="4"

# Links in utilities. Each element is "title","link"
# if title is blank, a separator is inserted
# CUSTOM_TOOL_LINKS = (
#     (_("Anar a google"), "https://www.google.es"),
#     (_("Anar a ICC"), "http://www.icgc.cat/"),
#     ("", ""),
#     (_("Conversió de coordenades - Convertbox"), "http://betaportal.icgc.cat/convertbox/#"),
#     (_("Conversió de coordenades - Earth Point: Convert coordinates"), "http://www.earthpoint.us/Convert.aspx"),
#     ("", ""),
#     (_("Georeferenciació - Geolocate"), "http://www.geo-locate.org/web/WebGeoref.aspx"),
#     (_("Georeferenciació - Georeferencing calculator"), "https://www.gbif.org/tool/81315/georeferencing-calculator"),
#     (_("Georeferenciació - Berkeley Mapper"), "http://berkeleymapper.berkeley.edu/#"),
# )

if os.getenv("DEBUG"): 
    try:
        from settings_debug import *
    except ImportError as e:
        pass    